# Generated by Django 6.0.1 on 2026-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_crashlog", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="crashevent",
            new_name="django_cras_created_1ce45b_idx",
            old_name="django_cra_created_f746c1_idx",
        ),
        migrations.RenameIndex(
            model_name="crashevent",
            new_name="django_cras_level_62a6b6_idx",
            old_name="django_cra_level_3c9407_idx",
        ),
        migrations.RenameIndex(
            model_name="crashevent",
            new_name="django_cras_logger_e527b9_idx",
            old_name="django_cra_logger_7ae3d1_idx",
        ),
        migrations.RenameIndex(
            model_name="crashevent",
            new_name="django_cras_error_t_b9f34d_idx",
            old_name="django_cra_error_t_75f241_idx",
        ),
        migrations.RenameIndex(
            model_name="crashevent",
            new_name="django_cras_request_2f726b_idx",
            old_name="django_cra_request_a77d3f_idx",
        ),
        migrations.RenameIndex(
            model_name="crashevent",
            new_name="django_cras_user_id_ed1547_idx",
            old_name="django_cra_user_id_714759_idx",
        ),
        migrations.RenameIndex(
            model_name="crashevent",
            new_name="django_cras_traceba_967e30_idx",
            old_name="django_cra_traceba_0a37ef_idx",
        ),
        migrations.AddField(
            model_name="crashevent",
            name="traceback",
            field=models.TextField(default="-"),
            preserve_default=False,
        ),
    ]
