# Generated by Django 6.0.1 on 2026-01-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_crashlog",
            "0002_rename_django_cra_created_f746c1_idx_django_cras_created_1ce45b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="crashevent",
            name="culprit",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="crashevent",
            name="server_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
