# Generated by Django 6.0.1 on 2026-01-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_crashlog", "0003_crashevent_culprit_crashevent_server_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crashevent",
            old_name="payload",
            new_name="context",
        ),
    ]
