# Generated by Django 6.0.1 on 2026-01-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_crashlog", "0004_rename_payload_crashevent_context"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crashevent",
            options={"ordering": ["-last_seen_at"]},
        ),
        migrations.RemoveIndex(
            model_name="crashevent",
            name="django_cras_traceba_967e30_idx",
        ),
        migrations.AddField(
            model_name="crashevent",
            name="last_seen_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="crashevent",
            name="occurrence_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="crashevent",
            name="traceback_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name="crashevent",
            index=models.Index(
                fields=["last_seen_at"], name="django_cras_last_se_94ed8a_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="crashevent",
            name="user_agent",
        ),
    ]
